<?php 
return array(
    'tickets' => 'tickets',
    'students' => 'students/admin',
    'students/create/<id:\d+>' => 'students/create',
    'students/update/<id>' => 'students/update/id/<id>',
    'students/delete/<id>' => 'students/delete/id/<id>',
    'schools' => 'schools/admin',
    'schools/update/<id>' => 'schools/update/id/<id>',
    'schools/delete/<id>' => 'schools/delete/id/<id>',
    'orders' => 'orders/admin',
    'orders/create/<id:\d+>' => 'orders/create',
    'orders/update/<id>' => 'orders/update/id/<id>',
    'orders/out/<id>' => 'orders/out/id/<id>',
    'orders/downloadlist' => 'orders/downloadlist',
    'orders/delete/<id>' => 'orders/delete/id/<id>',
    'promos/view/<id>' => 'promos/view/id/<id>',
    'promos/update/<id>' => 'promos/update/id/<id>',
    'promos/delete/<id>' => 'promos/delete/id/<id>',
    'years/create' => 'years/create',
    'years/delete/<id>' => 'years/delete/id/<id>',
    'divisions/create' => 'divisions/create',
    'divisions/delete/<id>' => 'divisions/delete/id/<id>',
    'schools-settings' => 'years',
    'products/create' => 'products/create',
    'products/update/<id>' => 'products/update/id/<id>',
    'products/delete/<id>' => 'products/delete/id/<id>',
    'users/update/<id>' => 'users/update/id/<id>',
    'users/delete/<id>' => 'users/delete/id/<id>',
    'more-settings' => 'setting/index',
    'salir' => 'site/logout',
    'login' => 'site/login',
    '<controller:\w+>/<action:\w+>'=>'<controller>/<action>',
);